DROP TABLE IF EXISTS prospects CASCADE;

CREATE TABLE prospects(
  id SERIAL,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  zip_code INT(5) NOT NULL,
  address VARCHAR(300) NOT NULL,
  address2 VARCHAR(300) NOT NULL,
  city VARCHAR(100) NOT NULL,
  state VARCHAR(100) NOT NULL,
  email VARCHAR(200) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  PRIMARY KEY (id)
);
